apiVersion: apps/v1
kind: Deployment
metadata:
  name: precedentia-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: docker.io/gabguimaraes/precedentia-web:79342ceb699bcba840442c8fd5f56e2d250a66b3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
