#!/usr/bin/env sh

echo
echo "🔍 Running flutter analyze..."
flutter analyze
if [ $? -ne 0 ]; then
  echo "❌ Flutter analyze failed. Commit aborted."
  exit 1
fi

echo
echo "🎨 Checking code formatting..."
dart format .
if [ $? -ne 0 ]; then
  echo "❌ Format failed."
  exit 1
fi

echo
echo "✅ All checks passed!"
