#!/usr/bin/env sh

echo
echo "🔍 Running flutter analyze..."
flutter analyze
if [ $? -ne 0 ]; then
  echo "❌ Flutter analyze failed. Commit aborted."
  exit 1
fi

echo
echo "🎨 Checking code formatting..."
dart format --set-exit-if-changed .
if [ $? -ne 0 ]; then
  echo "❌ Code is not formatted. Run 'dart format .'"
  exit 1
fi

echo
echo "✅ All checks passed!"
